// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddTokenToWhitelist(arg1:string):Promise<void>;

export function GetTopicPeerConfig(arg1:string):Promise<config.TopicPeerConfig>;

export function GetWhitelistedTokens():Promise<Array<string>>;

export function RemoveTokenFromWhitelist(arg1:string):Promise<void>;

export function SetTopicPeerConfig(arg1:string,arg2:config.TopicPeerConfig):Promise<void>;
