// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTokenToWhitelist(arg1) {
  return window['go']['main']['App']['AddTokenToWhitelist'](arg1);
}

export function GetTopicPeerConfig(arg1) {
  return window['go']['main']['App']['GetTopicPeerConfig'](arg1);
}

export function GetWhitelistedTokens() {
  return window['go']['main']['App']['GetWhitelistedTokens']();
}

export function RemoveTokenFromWhitelist(arg1) {
  return window['go']['main']['App']['RemoveTokenFromWhitelist'](arg1);
}

export function SetTopicPeerConfig(arg1, arg2) {
  return window['go']['main']['App']['SetTopicPeerConfig'](arg1, arg2);
}
